# Generated by Django 4.2.11 on 2024-10-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match_history',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
