# Generated by Django 4.2.11 on 2024-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_player_match_history_delete_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_name',
            field=models.CharField(default='default_profile_name', max_length=255, unique=True),
        ),
    ]
