# Generated by Django 4.2.16 on 2024-10-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticdata',
            name='player',
        ),
        migrations.DeleteModel(
            name='PingData',
        ),
        migrations.DeleteModel(
            name='TicData',
        ),
    ]
