# Generated by Django 4.2.16 on 2024-10-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friend',
            table='Friend',
        ),
    ]
