# Generated by Django 5.1.1 on 2024-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_player_friend_blocked_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_name',
            field=models.CharField(blank=True, default='default_username', max_length=255),
        ),
        migrations.DeleteModel(
            name='BlockedFriend',
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
