# Generated by Django 4.2.16 on 2024-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_player_blocked_users'),
        ('login', '0004_remove_friendship_friend_remove_friendship_user_and_more'),
    ]

    operations = [
    ]
