# Generated by Django 4.2.16 on 2024-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_merge_20241015_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='status_game',
        ),
    ]
