version: '3.8'

volumes:
  trance_volume:
  bd_volume:
  fd_volume:
  redis_volume:


networks:
  trance_network:
    name: trance_network
    driver: bridge

services:
  trance_db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_DB: "trance_db"
      POSTGRES_USER: "khbouych"
      POSTGRES_PASSWORD: "khbouych_pass"
    volumes:
      - trance_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - trance_network
    restart: always
  bd:
    build:
      context: ./bd
      dockerfile: back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - bd_volume:/app/vbd
    depends_on:
      - trance_db
    networks:
      - trance_network
    restart: always

  fd:
    build:
      context: ./fd
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - fd_volume:/app/vfd
    networks:
      - trance_network
    depends_on:
      - bd
    restart: always


  redis:
    image: redis:latest
    container_name: Trance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - trance_network
    restart: always
