version: '3.8'

# Define the volumes
volumes:
  postgres_volume:

    #networks:
networks:
  trance_network:
    name: trance_network
    driver: bridge

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - trance_network
    restart: always
  # Define the database service
  # trance_db:
  #   container_name: postgres_db
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: trance_db
  #     POSTGRES_USER: khbouych
  #     POSTGRES_PASSWORD: khbouych_pass
  #   volumes:
  #     - postgres_volume:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - trance_network
  #   restart: always

  # Define the backend service
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   # depends_on:
  #   #   - trance_db
  #   networks:
  #     - trance_network
  #   restart: always

    # Define the frontend service
    # nginx:
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #   command: [ nginx-debug, '-g', 'daemon off;' ]
    #   restart: always

    # Define the frontend service
    # redis:
    #   container_name: redis
    #   image: redis:alpine
    #   ports:
    #     - "6379:6379"
    #   networks:
    #     - trance_network
