version: "3.8"

volumes:
  db_volume:

services:
  postgres:
    container_name: dbpostgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - connexion
    restart: always

  back:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - connexion
    restart: always

  front:
    container_name: front
    build:
      context: ./front
    ports:
      - "5173:5173"
    networks:
      - connexion
    # volumes:
    #   - ./fd_volume:/app
    # depends_on:
    #   - back
    restart: always
networks:
  connexion:
    driver: bridge