version: "3.8"

volumes:
  db_volume:
networks:
  trance_network:
    name: trance_network
    driver: bridge

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - trance_network
    restart: always
  back:
    build:
      context: ./backend
      dockerfile: back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend_volume
    depends_on:
      - postgres
    networks:
      - trance_network
    restart: always

  front:
    build:
      context: ./front
      dockerfile: frontend/Dockerfile
    volumes:
      - ./front:/app/front_volume
    networks:
      - trance_network
    ports:
      - "5173:5173"
    restart: always

  # redis:
  #   image: redis:latest
  #   container_name: Trance_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_volume:/data
  #   networks:
  #     - trance_network
  #   restart: always
