# Generated by Django 4.2.16 on 2024-12-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('winner_profile_name', models.CharField(default='player', max_length=100)),
                ('loser_profile_name', models.CharField(default='player', max_length=100)),
                ('winner_avatar', models.URLField(default='default_player')),
                ('loser_avatar', models.URLField(default='default_player')),
                ('left_score', models.IntegerField()),
                ('right_score', models.IntegerField()),
                ('game_type', models.CharField(default='', max_length=100)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
