# Generated by Django 4.2.16 on 2024-10-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user', 'notif_type', 'game_type'), name='unique_pending_notification'),
        ),
    ]
