
FROM nginx:1.19.0-alpine

RUN apk update && apk add --no-cache openssl
RUN mkdir -p /etc/nginx/certs
RUN openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/key.key \
    -out /etc/nginx/certs/cert.crt \
    -subj "/C=MA/ST=khouribga/L=khouribga/O=1337/CN=10.13.1.9"

CMD ["nginx", "-g", "daemon off;"]
