
FROM nginx:1.19.0-alpine

# Copy the custom nginx configuration
COPY ngnix/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the SSL certificate and key

COPY ssl/ssl.crt /etc/nginx/ssl/ssl.crt
COPY ssl/ssl.key /etc/nginx/ssl/ssl.key

# Copy the frontend build files
COPY frontend/build/ /usr/share/nginx/html

# Expose the ports
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
