
FROM nginx:1.19.0-alpine

# Copy the custom nginx configuration
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update && apk add --no-cache openssl
RUN mkdir -p /etc/nginx/certs
RUN openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/key.key \
    -out /etc/nginx/certs/cert.crt \
    -subj "/C=MA/ST=kheribga/L=kheribga/O=42/CN=ft_trancendance.com"

# COPY ssl/ssl.crt /etc/nginx/ssl/ssl.crt
# COPY ssl/ssl.key /etc/nginx/ssl/ssl.key

# Copy the frontend build files
# COPY frontend/build/ /usr/share/nginx/html

# Expose the ports
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
