# Generated by Django 4.2.14 on 2024-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_friend_blockedfriend_blocked_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perc',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
