# Generated by Django 4.2.14 on 2024-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_perc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perc',
            new_name='percentage',
        ),
    ]
