# Generated by Django 4.2.14 on 2024-08-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_image_user_onlin_user_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='onlin',
            new_name='online',
        ),
    ]
